version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
    expose:
        - "9000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - order-db
    networks:
      - app-network

  order-nginx:
    image: nginx:latest
    container_name: order-nginx
    ports:
      - "8003:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - order-service
    networks:
      - app-network

  order-db:
    image: mysql:8.0
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: orders_db
      MYSQL_USER: orderuser
      MYSQL_PASSWORD: orderpass
    volumes:
      - order-db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  order-db-data:

networks:
  app-network:
    external: true
